### PR TITLE
Ecmwf mars forecast zonal stats

### PR DESCRIPTION
**Pull request by turnerm**
Sorry Zack just opening this PR for you because I wanted to leave a couple of comments, but please adjust the text / title / base etc!

### CODE REVIEW

**Comment by zackarno** [comment]
Thanks for the review - replying to your comments below:

> My main comments here are:
> 
> 1. For ECMWF ERA5 ground, it turns out that the hourly data is cumulative -- so the 00:00 value is the one we need. In the meantime I've written the extraction into Python, I will make a PR for that.
> 2. Not sure if you can just use the ERA5 data that we downloaded? Would make debugging a bit easier

- I think when I did this originally we did not have all the data or were note sure about that cumulative detail you described above so I just used daily data from GEE : ImageCollection: `ECMWF/ERA5_LAND/DAILY_RAW`.
- I just had a look at the downloaded ERA5 data and it looks like the folder is >386 GB. Not sure if this really makes sense to download and process when we can do it in seconds or minutes on the cloud with GEE? If we just pulled out 0:00 prior to downloading I bet it would be more feasible? However, not sure it's necessary with the GEE solution?

> 3. For ECMWF HRES, the rolling sums should be across lead time, not forecast date.

I think this is what I did, but perhaps I misunderstood something. I calculated the rolling sum for each forecast**ed** (not date of forecast) for each lead time. So the output has columns: 

- `date_forecast_predict` (representing date that was forecasted) 
-  `lead_n_rollx` (n = leadtime, x = number of days rolled)

here is just a preview of  the target `ecmwf_mars_leads_split_rolled` where this is done:

image

it looks right to me?

**Comment by zackarno** [comment]
Just opened this issue https://github.com/OCHA-DAP/pa-aa-yem-flooding/issues/15#issue-1682558131

**Comment by turnerm** [comment]
> I think when I did this originally we did not have all the data or were note sure about that cumulative detail you described above so I just used daily data from GEE : ImageCollection: ECMWF/ERA5_LAND/DAILY_RAW . I can re-run on the local files, but seems like you might have done this already from looking at the PRs above. I compared the GEE extraction values to the local files 00:00:00 value and they are equivalent (https://github.com/OCHA-DAP/pa-aa-yem-flooding/commit/f5a47ea728d7e367999e11d0aa2902ac12d5bb23), but worth noting that the local files 00:00:00 value is for the previous day so you can't simply convert the date times to dates without subtracting a day (i.e "2001-09-02 00:00:00" is the precip for 2001-09-01)

Ah yes, the 00:00 values is really the sum of the previous day. However in the local files, when I read it in with `xarray`, there is no 00:00 but 24:00, and it's the sum of the same day, so that's what I've been going with. 

> I think this is what I did, but perhaps I misunderstood something. I calculated the rolling sum for each forecastED date (not date of forecast) for each lead time.

The rolling sum should always be computed for the forecasted date, but the point is that you should take a single date of forecast, and compute the rolling sum only using the data from that (without mixing in other dates of forecast). Thus for 3-day rolling sum, you would end up with 8 lead times instead of 10. Hope this makes sense

**Comment by zackarno** [comment]
> The rolling sum should always be computed for the forecasted date, but the point is that you should take a single date of 
> forecast, and compute the rolling sum only using the data from that (without mixing in other dates of forecast). Thus for 3-> day rolling sum, you would end up with 8 lead times instead of 10. Hope this makes sense

ah yes i think that makes sense as that is how we would roll the values for assessing whether trigger threshold is crossed. 

I think had done it per lead time more for the purpose of assessing the skill/accuracy of the forecast (i.e comparing ERA5 and HRES) . My thinking was that we would be able to see how accurate each lead time is and that we might see that a lead time of 1 day give us some degree of confidence, but if we rolled the dates within the lead time of of 1 (i.e  3 day) we might see that we get a bit more confidence from the sort of smoothing effect. I think from preliminary charts we I made in the 09_ECMWF.html doc we do see this, but then again I'm not sure if this is totally necessary.

**Comment by zackarno** [comment]
> For ECMWF HRES, the rolling sums should be across lead time, not forecast date.

created new separate target for this [449c674](https://github.com/OCHA-DAP/pa-aa-yem-flooding/pull/12/commits/449c674de36eb5a500e0eb2c02c75a918a6dfb72)

**Pull request closed without merging**
